import axios from "axios"
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit"

const api = "https://fakestoreapi.com/products"

const initialState = {
  products: [],
}

//This is where async logic goes
export const fetchProducts = createAsyncThunk(
  "products/fetchProducts",
  async () => {
    const response = await axios.get(api)
    const data = await response.data
    return data
  }
)


export const productSlice = createSlice({
  name: "products",
  initialState,
  //The "reducers" field lets us define reducers and generate associated actions
  //This is where direct logic goes.
  reducers: {},
  // the "extraReducers" field lets the slice handle actions defined elsewhere,
  // including actions generated by creteAsyncThunk or in other slices

  // This is where async logic goes.
  extraReducers: (builder) => {
    builder
      .addCase(fetchProducts.fulfilled, (state, action) => {
        state.products = action.payload;
      })
      .addCase(fetchProducts.rejected, (state, action) => {
        state.product = []
      })
  }
})

export default productSlice.reducer;